### ISSUE TITLE
Fails to create new project (FileNotFoundError)

### ISSUE THREAD

**Issue by nazmulshuvo03** [facebookresearch/ClassyVision#575] opened 2020-07-23 15:15 UTC
## To Reproduce

1. pip3 install classy_vision
2. classy-project my-project

`Traceback (most recent call last):
  File "/home/nazmul/.local/bin/classy-project", line 47, in <module>
    shutil.copytree(template_path, destination_path)
  File "/usr/lib/python3.8/shutil.py", line 552, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.8/dist-packages/classy_vision/templates/synthetic'`

## Expected behavior

This should create a new project, according to the documentation.

## Environment

 - What commands did you use to install Classy Vision (conda/pip/build from source)? pip
 - If you are building from source, which commit is it?
 - What does `classy_vision.__version__` print? (If applicable): 0.4.0

Please copy and paste the output from the Pytorch
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.5.1
 - OS (e.g., Linux): Linux (Ubuntu)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.8.2
 - CUDA/cuDNN version: 10.1.243
 - GPU models and configuration: GeForce GT 710
- Nvidia driver version: 440.100
 - Any other relevant information:

## Additional context

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.1
[conda] Could not collect

**Comment by mannatsingh** [comment] 2020-07-23 20:33
This could possibly be a duplicate of https://github.com/facebookresearch/ClassyVision/issues/331. Are you using `virtualenv` by any chance @nazmulshuvo03 ?

**Comment by vreis** [comment] 2020-07-24 16:53
@nazmulshuvo03 : do you still get this error if you do the following steps:
```
conda create -n test_bug_575 python=3.6
conda activate test_bug_575
conda install pytorch torchvision -c pytorch
pip install classy_vision
classy-project my-project
```

**Comment by nazmulshuvo03** [comment] 2020-07-25 15:50
> This could possibly be a duplicate of #331. Are you using `virtualenv` by any chance @nazmulshuvo03 ?

No

**Comment by mannatsingh** [comment] 2020-07-27 17:28
@nazmulshuvo03 can you share the steps you used to install Python? It's probably related to that. 
In the mean time, can you try @vreis 's suggestion and let us know if it works for you?

**Comment by nazmulshuvo03** [comment] 2020-07-27 19:38
> @nazmulshuvo03 : do you still get this error if you do the following steps:
> 
> ```
> conda create -n test_bug_575 python=3.6
> conda activate test_bug_575
> conda install pytorch torchvision -c pytorch
> pip install classy_vision
> classy-project my-project
> ```

@vreis this works. but not the steps described in the docs (Getting started tutorial)
@mannatsingh python is preinstalled in Linux.

**Comment by mannatsingh** [comment] 2020-07-27 22:07
> @vreis this works. but not the steps described in the docs (Getting started tutorial)

Do you encounter a separate issue after using conda? Can you elaborate?

To see why this isn't working for your regular Python installation, can you let us know the output of the following -
```python
import classy_vision
print(classy_vision.__file__)
print(site.getsitepackages())
```

**Comment by mannatsingh** [comment] 2020-08-11 18:29
Closing this since there has been no response. Please re-open if you are still facing this issue.

**Closed by mannatsingh** 2020-08-11 18:29 UTC
