### ISSUE TITLE
GenericImageTransform sample type check

### ISSUE THREAD

**Issue by skyoung** [facebookresearch/ClassyVision#334] opened 2020-01-08 09:52 UTC
## 🐛 Bug

The `__call__()` of GenericImageTransform in `transform.utils` does not check whether input is a tuple or a dict. 

## To Reproduce
1. `classy-project my-project` to initialize an example project.
2. Set `SampleType.TUPLE` to `SampleType.DICT` in line 32 of `my_data.py`

## Expected behavior

`KeyError: Caught KeyError in DataLoader worker process 0.`

**Comment by aadcock** [comment] 2020-01-08 14:47
Hi skyoung! Thanks for reporting this. Unfortunately, it's not clear to me what the issue is (the repro produces the expected behavior you are asking for here).

Is the request for a clearer error message?

**Comment by skyoung** [comment] 2020-01-09 03:34
https://github.com/facebookresearch/ClassyVision/blob/9540125cbb0b396db29d239959d9a46476b7f83f/classy_vision/dataset/classy_dataset.py#L111-L113

Here `self.transform` expects a tuple and returns a dict. However, if `sample` is a tuple, and `self.transform==None`, it will return a tuple, which is inconsistent with the return when `self.transform is not None`

Therefore, I suggest that `self.transform` could accept a dict, and add a dict type check.

**Comment by vreis** [comment] 2020-02-11 02:51
Closing this out. @skyoung feel free to re-open if the PR didn't address your issue.

**Closed by vreis** 2020-02-11 02:51 UTC
